---
title: "CSM Match Analysis Script"
author: "Ashley J. Coventry, Daniel Conroy-Beam"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(dplyr)
library(lmerTest)
library(ggplot2)
library(ggmosaic) # for plotting
library(PairedData) #to test if variance in attractiveness ratings differs by condition
library(psych) #for ICC function
library(data.table) #for melt function
library(ggpubr) 
library(viridis) #for card use graph
library(car) #for levene's test

```

```{r functions}
#for computing euclidean distance

mv<-function(ideal,traits){
  
  mv<-(-1*dist(rbind(ideal,traits))+sqrt(10^2*15))/sqrt(10^2*15)
  
  return(mv)
  
}

```

```{r loading data}

matchData <- read.csv('human-data/processed-data/matchDataProcessed 042725.csv')


data <- read.csv('human-data/processed-data/postDateProcessed 042725.csv')

```

```{r demographics}

participantAge <- summary(matchDataFiltered$age)
participantQuarter <- table(matchDataFiltered$quarter)
participantSex <- table(matchDataFiltered$sex)
participantSexOrient <- table(matchDataFiltered$sexOrient)
participantGender <- table(matchDataFiltered$gender)


#race
matchDataFiltered$raceText<- apply(matchDataFiltered[, 10:16], 1, function(x) {
  selected <- which(x == 1)
  
  if (length(selected) == 0) {
    return(NA)  # No race selected
  } else if (length(selected) == 1) {
    return(names(x)[selected])  # Only one race selected
  } else {
    return("Multiracial")  # Multiple races selected
  }
})

participantRace <- table(matchDataFiltered$raceText)

```

```{r descriptives}

numDates <- nrow(data)

numSubjects <- length(unique(data$PIN))

numSubjectsTwoDates <- data %>%
  count(PIN) %>%
  filter(n == 2) %>%
  summarise(num_twice = n())

numSubjectsOneDate <- data %>%
  count(PIN) %>%
  filter(n == 1) %>%
  summarise(num_once = n())

numDatesByCondition <- table(data$c)

attractionSummary <- summary(data$ltAttraction) #one NA? 
histAttraction <- hist(data$ltAttraction)

nextDateSummary <- summary(data$dateInterest) #again one NA
histNextDate <- hist(data$dateInterest)

tableExchange <- table(data$contactExchange, data$c)


##Create dataframe with only participants who completed both dates##

#first see who mutually exchanged contact info
data$contactReceive<-sapply(1:nrow(data),function(x)
  data$contactExchange[data$PIN==data$mPIN[x] & data$mPIN==data$PIN[x]]
) #basically 1 if partner wanted to exchange info with them, 0 if they didn't

#find mutuals
mutuals <- data[sapply(1:nrow(data), function(x) {
  self_exchange <- data$contactExchange[x]
  
  # Find the reciprocal index
  reciprocal <- which(data$PIN == data$mPIN[x] & data$mPIN == data$PIN[x])
  
  # Check if both sides exchanged contact
  if (length(reciprocal) == 1) {
    return(self_exchange & data$contactExchange[reciprocal])
  } else {
    return(FALSE)  # not mutual if there's no clean match
  }
}), c("PIN", "mPIN")]


#column for number of dates
data <- data %>% 
  group_by(PIN) %>%
  mutate(numDates = n()) %>%
  ungroup()
#only those who had two dates
dataComplete <- data %>%
  filter(numDates == 2)

#make people in match data same as those in dataComplete
matchDataFiltered <- matchData %>%
  filter(PIN %in% dataComplete$PIN)

dataComplete$date<-sapply(1:nrow(dataComplete),function(x)
  ifelse(dataComplete$sex[x]==0,paste0(dataComplete$PIN[x],dataComplete$mPIN[x]),
         paste0(dataComplete$mPIN[x],dataComplete$PIN[x]))
  )


```

```{r rating agreement & prefMatch calc}

##calculate perception accuracy 

#correlation between impressions of partner and date's self ratings
colnamesTraits <- c("Affectionate", "Ambition", "Artistic", "Disposition", "Family", "Health", "Humor", "Intelligence", 
                    "Kindness", "Parenting", "PhysAtt", "Religious", "Resources", "Sexiness", "Status")

traitCors <- data.frame("trait" = colnamesTraits, 
                        "cor" = round(diag(cor(dataComplete[,115:129],
                                               dataComplete[,160:174],
                                               use = "pairwise.complete.obs")), 3))


#mate preference fulfillment based on impressions of partners (vs partner's actual self reported traits)
dataComplete$prefMatch <- apply(dataComplete, 1, function(x)
  mv(x[145:159], x[115:129])) #first is ideals, second is ratings of date


#prefMatch by condition
prefMatchCondition <- tapply(dataComplete$prefMatch,list(dataComplete$c,dataComplete$sex),mean)



#pre and post ideals correlation
dataPreAndPost <- dataComplete %>%
  left_join(dplyr::select(matchDataFiltered, PIN, idealAffectionComp: idealStatusComp) %>%
              rename_with(~paste0(., "T1"), -PIN), 
            by = "PIN")


#pre date and post date ideals correlation
traitCorsPrePost <- data.frame("trait" = colnamesTraits, 
                        "cor" = round(diag(cor(dataPreAndPost[,179:193],
                                               dataPreAndPost[,145:159],
                                               use = "pairwise.complete.obs")), 3))


```

```{r Main Manuscript Analyses}


###ANALYSES###


#Are participants' matched dates a better match to their preferences? (not pre-registered)

dataComplete$prefMatchActual <- apply(dataComplete, 1, function(x)
  mv(x[145:159], x[160:174])) #first is ideals, second is date's ratings of themselves

prefMatchActualModel <- lmer(scale(prefMatchActual) ~ c + (1|PIN) + (1|mPIN), data = dataComplete)

prefMatchConditionActual <- tapply(dataComplete$prefMatchActual,list(dataComplete$c,dataComplete$sex),mean)


##SECOND DATE INTEREST

#Do matched dates result in greater second date interest? (pre-registered)

secondDateModel <- lmer(scale(dateInterest) ~ c + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome
secondDateModelSexMain <- lmer(scale(dateInterest) ~ c*sex + (1|PIN) + (1|mPIN), 
  data = dataComplete) #no sig int


#Is interest in a second date predicted by prefMatch*dateSecondDateInterest? (not pre-registered)
dateInterestReciprocityModel <-lmer(scale(dateInterest)~scale(dateInterestDate)*scale(prefMatch)+(1|PIN)+(1|mPIN),data=dataComplete)


##LT ATTRACTION

#Do matched dates result in greater romantic attraction? (pre-registered)
attractionModel <- lmer(scale(ltAttraction) ~ c + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome
attractionModelSexMain <- lmer(scale(ltAttraction) ~ c*sex + (1|PIN) + (1|mPIN), 
  data = dataComplete) #no sig int 

#Is romantic attraction predicted by pref match? (not pre-registered)
dataComplete$c <- as.factor(dataComplete$c)

attractionModelPerceived <- lmer(scale(ltAttraction) ~ c + scale(prefMatch) + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome
attractionModelPerceivedOnly <- lmer(scale(ltAttraction) ~ scale(prefMatch) + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome

#Is romantic attraction predicted by pref match (with pre-date ideals)? (not pre-registered)
dataComplete$prefMatchPre <- sapply(1:nrow(dataComplete), function(x)
  mv(as.numeric(matchData[match(dataComplete$PIN[x], matchData$PIN), 53:67]), #ideals time 1
     as.numeric(dataComplete[x, 115:129]))) #date ratings

attractionModelPerceivedPreDate <- lmer(scale(ltAttraction) ~ scale(prefMatchPre) + c + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome

#Is romantic attraction predicted by pref match (with pre-date ideals and partner's self-reported traits, not perceptions)
dataComplete$prefMatchPreAndDateSelfRatings <- sapply(1:nrow(dataComplete), function(x)
  mv(as.numeric(matchData[match(dataComplete$PIN[x], matchData$PIN), 53:67]), #ideals time 1
     as.numeric(dataComplete[x, 160:174]))) #date ratings

attractionModelDateRatingsAndPreDate <- lmer(scale(ltAttraction) ~ scale(prefMatchPreAndDateSelfRatings) + c + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome

#Is romantic attraction predicted by prefMatch*dateLtAttraction? 
ltAttractionReciprocityModel<-lmer(scale(ltAttraction)~scale(ltAttractionDate)*scale(prefMatch)+(1|PIN)+(1|mPIN),data=dataComplete)

##CONTACT EXCHANGE


#Is contact exchange (yes/no) predicted by condition? 

contactExchangeModel <- glmer(contactExchange ~ c + (1|PIN) + (1|mPIN),
  data = dataComplete, family = binomial,
  control = glmerControl(optimizer = "optimx", optCtrl = list(method = "nlminb", iter.max = 10000, eval.max = 10000))) #need optimizer to fix convergence issue

contactExchangeModelSexMain <- glmer(contactExchange ~ c*sex + (1|PIN) + (1|mPIN), 
  data = dataComplete, family = binomial)#no sig int

```

```{r Supplemental Materials: Pre-registered Analyses}

##chi square test looking at relationship between condition (matched vs random) and contact exchange (yes/no)
chisqTestConditionByExchange <- chisq.test(table(dataComplete$c, dataComplete$contactExchange))

##t-test: variance in romantic interest by condition
varConditionR <- var(dataComplete$ltAttraction[dataComplete$c == "r"])
varConditionS <- var(dataComplete$ltAttraction[dataComplete$c == "s"], na.rm = TRUE) #one NA case
varTest <- car::leveneTest(ltAttraction ~ c, data = dataComplete) #to test if they are significantly different (can't do F-test bc not normally distributed)

##sexual attraction
stAttractionCondition <- lmer(scale(stAttraction) ~ c + (1|PIN) + (1|mPIN), data = dataComplete)
stAttractionModelPrefMatch <- lmer(scale(stAttraction) ~ c + scale(prefMatch) + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome
stAttractionReciprocityModel<-lmer(scale(stAttraction)~scale(stAttractionDate)*scale(prefMatch)+(1|PIN)+(1|mPIN),data=dataComplete)


```

```{r Supplemental Materials: Analyses not pre-registered}

##PERMUTATION TEST
set.seed(1220)

#make new df just for this
permutationData <- dataComplete[,c(113, 114, 110, 145:159, 115:129, 94:96, 100)]

#add blank columns for shuffling
shuffledNames <- paste0(names(permutationData[,4:18]), "Shuffled")
permutationData[,shuffledNames] <- NA_real_

#loop number
nLoop <- 50000

#df to save loop output
permutationRecord <- data.frame(
                  estimate=rep(NA,nLoop),
                  t=rep(NA,nLoop),
                  p=rep(NA,nLoop))
##For Loop

for (i in 1:nLoop){
#recalculate pref match with shuffled prefs
permutationData[shuffledNames] <- t(apply(permutationData[,4:18], 1, sample)) #1 here makes this row by row


#mate preference fulfillment based on impressions of partners & shuffled ideals
permutationData$prefMatchPermutation <- apply(permutationData, 1, function(x)
  mv(x[38:52], x[19:33])) #first is shuffled ideals, second is ratings of date

#redoing lt attraction model with shuffled prefs
attractionModelPerceivedOnlyPermutation <- lmer(scale(ltAttraction) ~ scale(prefMatchPermutation) + (1|PIN) + (1|mPIN), data = permutationData)

#save estimate, t value, p value
permutationRecord$estimate[i]<-summary(attractionModelPerceivedOnlyPermutation)$coefficients[2,1]
permutationRecord$t[i]<-summary(attractionModelPerceivedOnlyPermutation)$coefficients[2,4]
permutationRecord$p[i]<-summary(attractionModelPerceivedOnlyPermutation)$coefficients[2,5]
}

#get 95% CI with quantile function

permutationCI <- quantile(permutationRecord$t, probs = c(0.025, 0.975))



##PHYS ATT: is physical attractiveness, not preference match, just responsible for increased attraction to certain partners?##

#romantic attraction
attractionModelPhysAtt <- lmer(scale(ltAttraction) ~ c +  scale(datePhysattComp) + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome
attractionModelPhysAttPrefMatch <- lmer(scale(ltAttraction) ~ scale(prefMatch) + scale(datePhysattComp) + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome

#second date interest
secondDateModelPhysAtt <- lmer(scale(dateInterest) ~ c + scale(datePhysattComp) + (1|PIN) + (1|mPIN), data = dataComplete) #standardized outcome
secondDateModelPhysAttPrefMatch <- lmer(scale(dateInterest) ~ scale(prefMatch) + scale(datePhysattComp) + (1|PIN) + (1|mPIN), data = dataComplete)

#contact exchange
contactExchangeModelPhysAtt <- glmer(
  contactExchange ~ c + scale(datePhysattComp) + (1|PIN), #remove 1|mPIN bc vcov = 0 and causing singular fit issues
  data = dataComplete,
  family = binomial)

contactExchangeModelPhysAttPrefMatch <- glmer(
  contactExchange ~ scale(prefMatch) + datePhysattComp + (1|PIN) + (1|mPIN), 
  data = dataComplete,
  family = binomial)


```

```{r Card use analyses - Not Reported}

##Is perception accuracy predicted by card use?
dataMelt<-melt(as.data.table(data),id.vars=c("PIN","mPIN","cardUse"),
               measure.vars=list(115:129,160:174),
               value.name=c("date","mate")) #date = participant rating of their date; mate = partner's rating of themselves

dataMelt$variable<-rep(colnames(data[,160:174]),each=nrow(data))

dataMelt$variable<-gsub("mate","",dataMelt$variable)
dataMelt$variable<-gsub("Comp","",dataMelt$variable)

dataMelt$variable<-factor(dataMelt$variable)

cardEffectModel<-lmer(date~mate*cardUse+(1|PIN)+(1|mPIN),data=dataMelt)


##Are outcome variables predicted by card use? 

dateInterestCardUseModel <- lmer(scale(dateInterest) ~ scale(cardUse) + scale(prefMatch) + (1|PIN) + (1|mPIN), data = dataComplete)
ltAttractionCardUseModel <- lmer(scale(ltAttraction) ~ scale(cardUse) + scale(prefMatch) + (1|PIN) + (1|mPIN), data = dataComplete)
contactExchangeCardUseModel <- glmer(contactExchange ~ scale(cardUse) + scale(prefMatch) + (1|PIN) + (1|mPIN), data = dataComplete, family = binomial)

```

```{r Plots}


dataComplete$contactRecip<-ifelse(dataComplete$contactExchange==1 & dataComplete$contactReceive==1,
                                  "Mutual Exchange",ifelse(
                                    dataComplete$contactExchange==0 & dataComplete$contactReceive==0,
                                    "Mutual Reject","One Exchange"
                                  ))

dataComplete$contactExchange<-factor(dataComplete$contactExchange,labels=c("Not Shared","Shared"))
dataComplete$contactReceive<-factor(dataComplete$contactReceive,labels=c("Not\nShared","Shared"))

sTable<-round(prop.table(table(dataComplete$contactReceive[dataComplete$c=="s"],
                         dataComplete$contactExchange[dataComplete$c=="s"])),2)

rTable<-round(prop.table(table(dataComplete$contactReceive[dataComplete$c=="r"],
                         dataComplete$contactExchange[dataComplete$c=="r"])),2)



#Plot contact exchange for random dates
exchangePlotS <- ggplot(data = dataComplete[dataComplete$c=="s",],) +
  geom_mosaic(aes(x = product(contactReceive, contactExchange)),
              fill=c("black","grey30","grey30","#009E73"))  +
  labs(x = "Participant Phone Number", y = "Partner Phone Number") +
  annotate(
    "text",
    x = c(.25, .75, .25, .75),
    y = c(sTable[1,1]/sum(sTable[,1])/2,
          sTable[1,2]/sum(sTable[,2])/2,
          1-sTable[2,1]/sum(sTable[,1])/2,
          1-sTable[2,2]/sum(sTable[,2])/2),
    label = paste0(100*sTable, "%")[c(1,3,2,4)],
    size = 12,
    color="white"
  ) +
  theme(
    text = element_text(size = 35),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  ggtitle("a", subtitle = "Randomly-matched dates")

#ggsave("Figures/CSM Match Random Exchange Plot.tiff",exchangePlotS,height=10,width=10,dpi=300)



#Plot contact exchange for matched dates
exchangePlotR <- ggplot(data = dataComplete[dataComplete$c=="r",],) +
  geom_mosaic(aes(x = product(contactReceive, contactExchange)),
              fill=c("black","grey30","grey30","#009E73"))  +
  labs(x = "Participant Phone Number", y = "Partner Phone Number") +
  annotate(
    "text",
    x = c(.15, .66, .15, .66),
    y = c(rTable[1,1]/sum(rTable[,1])/2,
          (rTable[1,2]/sum(rTable[,2]))/2,
          1-rTable[2,1]/sum(rTable[,1])/2,
          1-rTable[2,2]/sum(rTable[,2])/2),
    label = paste0(100*rTable, "%")[c(1,3,2,4)],
    size = 12,
    color="white"
  ) +
  theme(
    text = element_text(size = 35),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )+
  ggtitle("b", subtitle = "Algorithm-matched dates")

#ggsave("Figures/CSM Match Matched Exchange Plot.tiff",exchangePlotR,height=10,width=10,dpi=300)

#combined contact exchange plots
combinedContactPlot <- ggarrange(exchangePlotS + theme(axis.title = element_blank()),
                                 exchangePlotR + theme(axis.title = element_blank()),
                                 ncol = 2)
combinedContactPlot <- annotate_figure(combinedContactPlot, left = text_grob("Date Share Choice", rot = 90, size = 30),
                                       bottom = text_grob("Participant Share Choice", size = 30))

#ggsave("Figures/CSM Match Matched Exchange Plot Combined.jpeg",combinedContactPlot,height=10,width=20,dpi=300)

##interest plot

#variables
dataComplete$interestJitter<-jitter(dataComplete$dateInterest)
dataComplete$cPref<-sapply(1:nrow(dataComplete),function(x)
  ifelse(dataComplete$dateInterest[dataComplete$PIN==dataComplete$PIN[x] & dataComplete$c=="r"]>
           dataComplete$dateInterest[dataComplete$PIN==dataComplete$PIN[x] & dataComplete$c=="s"],
                  "Matched Higher",
                  ifelse(dataComplete$dateInterest[dataComplete$PIN==dataComplete$PIN[x] & dataComplete$c=="s"]>
                                  dataComplete$dateInterest[dataComplete$PIN==dataComplete$PIN[x] & dataComplete$c=="r"],
                                "Random Higher","Equal")
  )
)




interestPlot<-ggplot(data=dataComplete,
     aes(x=factor(c,labels=c("Matched","Random")),
         y=interestJitter,
         color=cPref,
         group=PIN))+
  geom_point()+
  geom_line()+
  labs(x="Condition",
     y="Interest in Another Date")+
  theme(text=element_text(size=25),legend.position="none")+
  stat_summary(aes(group=1),
             fun="mean",geom="line",color=I("black"),lwd=2.5)+
  scale_color_manual(values=c("#004D40","#D81B60","#1E88E5"))


interestDiff<-data.frame(tapply(dataComplete$dateInterest,list(dataComplete$PIN,dataComplete$c),mean))
interestDiff$diff<-interestDiff[,1]-interestDiff[,2]

interestViolin<-ggplot(data=interestDiff,
       aes(y=diff,x=1,
           fill=I("#1E88E5")))+
  geom_violin(alpha=.5)+
  geom_boxplot(width=.1,alpha=.5)+
  geom_hline(yintercept=mean(interestDiff$diff,na.rm=T),color="#D81B60",lwd=2)+
  geom_hline(yintercept=0,color="#004D40",lwd=2)+
  labs(y="Date Interest Difference\n(Matched - Random)",x="")+
  theme(text=element_text(size=25))+
  scale_x_continuous(breaks=c())+
  scale_y_continuous(breaks=seq(-6,6,2))





#plot of partner self ratings and participant rating of partner
impressionPlot<-ggplot(data=dataMelt,
       aes(x=mate,
           y=date,
           color=variable))+
  labs(x="Partner Self Rating",
       y="Participant Rating of Partner",
       color="Trait Dimension")+
  theme(text=element_text(size=25),legend.position="none")+
  coord_cartesian(ylim=c(0,10),xlim=c(0,10))+
  geom_jitter(size=2)+
  geom_smooth(method="lm",se=F)



#Attraction by condition
attractionViolin <- ggplot(dataComplete, aes(x = c, y = scale(ltAttraction), fill = c)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.3, outlier.shape = NA, size = 1, fill = "white") +  
  labs(x = "Condition", y = "Long-Term Attraction (standardized)") + 
  scale_x_discrete(labels = c("r" = "Matched Date", "s" = "Random Date")) +
  scale_fill_manual(values = c("r" = "#B6284E", "s" = "#F39E44")) +
  theme_minimal()+
  theme(text=element_text(size=25),legend.position="none")
#ggsave("Figures/CSM Match Attraction Violin Plot.tiff",attractionViolin,height=10,width=10,dpi=300)

##Attraction by prefmatch
interestPrefMatchPlot <- ggplot(dataComplete, aes(x = scale(prefMatch), y = scale(ltAttraction)))+
  geom_jitter(width = .07, height = .07, alpha = .03) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "#28B68F") +
  labs(
    x = "Perceived Match of Date's Traits to Reported Ideals \n(Standardized)",
    y = "Romantic Attraction to Date (Standardized)"
  ) +
  theme_minimal() +
  theme(text=element_text(size=25))
#ggsave("Figures/CSM Match Interest PrefMatch Plot.tiff",interestPrefMatchPlot,height=10,width=10,dpi=300)





##Date interest by condition
secondDateViolin <- ggplot(dataComplete, aes(x = c, y = scale(dateInterest), fill = c)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.3, outlier.shape = NA, size = 1, fill = "white") +  # add boxplots inside violins
  labs(x = "Condition", y = "Interest in a Second Date (Standardized)") +
  scale_x_discrete(labels = c("r" = "Matched Date", "s" = "Random Date")) +
  scale_fill_manual(values = c("r" = "#B6284E", "s" = "#F39E44")) +
  theme_minimal()+
  theme(text=element_text(size=25),legend.position="none")
#ggsave("Figures/CSM Match Second Date Violin Plot.tiff",secondDateViolin,height=10,width=10,dpi=300)




##prefMatch by condition
prefMatchActualViolin <- ggplot(dataComplete, aes(x = c, y = scale(prefMatchActual), fill = c)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.3, outlier.shape = NA, size = 1, fill = "white") +
  labs(x = "Condition", y = "Actual Match Between Participant Ideals \nand Date Traits (Standardized)")+
  scale_x_discrete(labels = c("r" = "Matched Date", "s" = "Random Date")) +
  scale_fill_manual(values = c("r" = "#B6284E", "s" = "#F39E44")) +
  theme_minimal()+
  theme(text = element_text(size = 25), legend.position = "none")
#ggsave("Figures/CSM Match Actual Pref Match.tiff",prefMatchActualViolin,height=10,width=10,dpi=300)



##Romantic attraction & second date interest as a function of prefmatch and perceived date attraction
dataComplete <- dataComplete %>%
  mutate(ltAttractionDateBinned = ntile(ltAttractionDate, 2), 
         ltAttractionDateBinned = factor(ltAttractionDateBinned, levels = c(1,2), 
                                     labels = c("Below Median", "Above Median"))) %>%
  filter(!is.na(ltAttractionDateBinned))

attractionPrefMatchDateAttractionPlot <- ggplot(dataComplete, aes(x = scale(prefMatch), y = scale(ltAttraction), color = ltAttractionDateBinned, fill = ltAttractionDateBinned)) +
  geom_jitter(width = .07, height = .07, alpha = .03) +
  geom_point(alpha = .3)+
  geom_smooth(method="lm", se = TRUE, color = "black") +
  labs(x = "Perceived Preference Match (Standardized)", 
       y = "Romantic Attraction to Date (Standardized)",
       fill = "Perceptions of Date's Romantic Attraction\n(Standardized & Binned)")+
  scale_color_manual(
    guide = "none",
    values = c("Below Median" = "#28B6B1",
               "Above Median" = "#C25577"))+
  scale_fill_manual(
    values = c("Below Median" = "#28B6B1",
               "Above Median" = "#C25577"))+
  theme_minimal()+
  theme(text = element_text(size = 25))

#ggsave("Figures/CSM Match attractionFromDateAttraction.tiff",attractionPrefMatchDateAttractionPlot,height=10,width=15,dpi=300)


##second date interest by prefMatch
dataComplete <- dataComplete %>%
  mutate(dateInterestDateBinned = ntile(dateInterestDate, 2), 
         dateInterestDateBinned = factor(dateInterestDateBinned, levels = c(1,2), 
                                     labels = c("Below Median", "Above Median"))) %>%
  filter(!is.na(dateInterestDateBinned))

interestPrefMatchDateInterestPlot <- ggplot(dataComplete, aes(x = scale(prefMatch), y = scale(dateInterest), color = dateInterestDateBinned, fill = dateInterestDateBinned)) +
  geom_jitter(width = .07, height = .07, alpha = .03) +
  geom_point(alpha = .3)+
  geom_smooth(method="lm", se = TRUE, color = "black") +
  labs(x = "Perceived Preference Match (Standardized)", 
       y = "Interest in a Second Date (Standardized)",
       fill = "Perceptions of Date's Second Date Interest\n(Standardized & Binned)")+
  scale_color_manual(
    guide = "none",
    values = c("Below Median" = "#28B6B1",
               "Above Median" = "#C25577"))+
  scale_fill_manual(
    values = c("Below Median" = "#28B6B1",
               "Above Median" = "#C25577"))+
  theme_minimal()+
  theme(text = element_text(size = 25))
#ggsave("Figures/CSM Match interestFromDateInterest.tiff",interestPrefMatchDateInterestPlot,height=10,width=15,dpi=300)


##sexual attraction as an interaction of prefMatch and perceptions of the date partner's reciprocal sexual attraction
dataComplete <- dataComplete %>%
  mutate(stAttractionDateBinned = ntile(stAttractionDate, 2), 
         stAttractionDateBinned = factor(stAttractionDateBinned, levels = c(1,2), 
                                     labels = c("Below Median", "Above Median"))) %>%
  filter(!is.na(stAttractionDateBinned))

sexualAttractionPrefMatchDateAttractionPlot <- ggplot(dataComplete, aes(x = scale(prefMatch), y = scale(stAttraction), color = stAttractionDateBinned, fill = stAttractionDateBinned)) +
  geom_jitter(width = .07, height = .07, alpha = .03) +
  geom_point(alpha = .3)+
  geom_smooth(method="lm", se = TRUE, color = "black") +
  labs(x = "Perceived Preference Match (Standardized)", 
       y = "Sexual Attraction to Date (Standardized)",
       fill = "Perceptions of Date's Sexual Attraction\n(Standardized & Binned)")+
  scale_color_manual(
    guide = "none",
    values = c("Below Median" = "#28B6B1",
               "Above Median" = "#C25577"))+
  scale_fill_manual(
    values = c("Below Median" = "#28B6B1",
               "Above Median" = "#C25577"))+
  theme_minimal()+
  theme(text = element_text(size = 25))
#ggsave("Figures/CSM Match sexualAttractionFromDateAttractionPrefMatch.tiff",sexualAttractionPrefMatchDateAttractionPlot,height=10,width=15,dpi=300)


```







