---
title: "CSM-Match Processing Script"
author: "Ashley J. Coventry, Daniel Conroy-Beam"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages

```{r packages}
library(dplyr)

```



```{r loading data}

#load in post-date data
data <- read.csv('human-data/raw-data/CSM Match Post-Date Raw 041625.csv')

#load in prescreen data
matchDataF <- read.csv('human-data/processed-data/CSM-Match-matching-data-F24.csv')

matchDataW <- read.csv('human-data/processed-data/CSM-Match-matching-data-W25.csv')

```

```{r processing}

#remove title rows
data <- data[-c(1:2),]

#remove participants outside of fall and winter (based on start date)
data <- data %>%
  mutate(StartDate = as.POSIXct(StartDate, format = "%Y-%m-%d %H:%M:%S")) %>%
  filter(StartDate >= as.POSIXct("2024-09-22 00:00:00"))


#add in "quarter" column
data$quarter <- ifelse(data$StartDate <= as.POSIXct("2025-01-06 00:00:00"), "fall", "winter")

matchDataF$quarter <- "fall"
matchDataW$quarter <- "winter"
matchDataComplete <- rbind(matchDataF, matchDataW)


#extract PINs
data$PIN<-sapply(data$p,function(x)
  strsplit(x,"_")[[1]][1]
  )

data$mPIN<-sapply(data$p,function(x)
  strsplit(x,"_")[[1]][2]
)


#now check to make sure every date has a reciprocal
#logical vector: TRUE if the reciprocal exists
reciprocalPIN <- sapply(1:nrow(data), function(x) {
  any(data$PIN == data$mPIN[x] & data$mPIN == data$PIN[x])
})

#fix incorrect p & c's
data[63, "p"] <-"f24677880_f2458021" #changed from f24677880_f24173430
data[63, "c"] <- "s"

data[328,"p"] <- "f2414182_f24102355" #changed from f2414182_f24467836 
data[328, "c"] <- "r"

data[361, "p"] <- "f24423571_f24632338" #changed from f24423571_f24275843
data[361, "c"] <- "s"

data[371, "p"] <- "f24617278_f24480688" #changed from f24617278_f24848147
data[371, "c"] <- "r"



#redo extracting PINs
data$PIN<-sapply(data$p,function(x)
  strsplit(x,"_")[[1]][1]
  )

data$mPIN<-sapply(data$p,function(x)
  strsplit(x,"_")[[1]][2]
)


#RAs accidentally used same PIN_mPIN string for both dates, so checking for duplicate date IDs 

#get row of duplicates
dupIndices <- which(duplicated(data$p) | duplicated(data$p, fromLast = TRUE))

#dups resulted from empty rows -- delete empty rows (participant opened survey twice, only completed one tab) & test row (row 275)
data <- data[-c(83, 264, 275),]


#same day
data$StartDate <- as.Date(data$StartDate)
sameDayDates <- data %>% 
  count(PIN, StartDate) %>%
  filter(n>1)

#remove unnecessary columns
data <- data[18:131]


#make all relevant columns numeric
data <- data %>%
  mutate(across(c(1, 3:101, 106:108), ~ as.numeric(as.character(.))))


#make post-date preference,ideals, own ratings 0-10 scale
data[,c(4:93)] <- data[,c(4:93)] - 1



#make composites of ideals, prefs, and mate actuals in post-date data

mate<-data[,4:33]
self<-data[,34:63]
ideals <- data[,64:93]

#actual mate composites
mateComp <- sapply(seq(1,30,2),function(x)
  rowMeans(mate[,(x:(x+1))],na.rm=T)
  )
colnames(mateComp)<-gsub(1,"Comp",colnames(mate)[seq(1,30,2)])

#ideal composites
idealComp<-sapply(seq(1,30,2),function(x)
  rowMeans(ideals[,(x:(x+1))],na.rm=T)
  )
colnames(idealComp)<-gsub(1,"Comp",colnames(ideals)[seq(1,30,2)])

#self composites
selfComp<-sapply(seq(1,30,2),function(x)
  rowMeans(self[,(x:(x+1))],na.rm=T)
  )
colnames(selfComp)<-gsub(1,"Comp",colnames(self)[seq(1,30,2)])

#add comps to post-date data frame
data<-cbind(data, mateComp, selfComp, idealComp)


#rearrange data so participants' self ratings appear with their date's ratings of them
#issue: each person potentially appears more than once // this will grab just theri first appearance
partnerRatings<-as.data.frame(selfComp[match(data$mPIN,data$PIN),])
colnames(partnerRatings)<-gsub("self","mate",names(partnerRatings))

#Add partner ratings to same line as corresponding participant
data<-cbind(data,partnerRatings) #partnerRatings = partner's ratings of themselves

```


```{r save data}

#post date data
write.csv(data,"human-data/processed-data/postDateProcessed 042725.csv",
          row.names=F)

#match data
write.csv(matchDataComplete,"human-data/processed-data/matchDataProcessed 042725.csv",
          row.names=F)

```


