```{r loadData}
#Set seed
set.seed(20241015)

#Load the data
data<-read.csv("human-data/processed-data/CSM-Match-matching-data-F24.csv")

#Recode DQs to 0 or 1 rather than 1 or NA
data[,c(20:52)]<-ifelse(is.na(data[,c(20:52)]),0,1)

```




```{r params}


#Number of Observations#
#Total number of observation opportunities agents will have in mate search
nobs<-30*nrow(data)/2

```




```{r functions}

#MV calculation#
mvCalc <- function(ideal,
                   ageDq,
                   raceDq,
                   religionDq,
                   politicsDq,
                   intDQ,
                   traits,
                   age,
                   race,
                   religion,
                   politics,
                   int) {
  #ideal is ideal preferences
  #ageDq is age disqualifiers
  #raceDq is race disqualifiers
  #religionDq is religion disqualifiers
  #politicsDq is politics disqualifiers
  #intDQ is international student status disqualifiers
  #traits is actual trait values
  #age is age of the participant
  #race is participants' race/ethnicity
  #religion is participants' religion
  #politics is participants' politics
  #int is internatioanl student status
  
  
  
  #Continuous Preferences#
  
  #Calculates Euclidean distance between preferences and traits
  #Transforms this distance such that positive values are more attractive
  mv <- apply(traits, 1, function(x)
    sum((as.numeric(ideal) - x) ^ 2))
  
  
  
  #Disqualifiers#
  
  #Age:
  
  #Create a variable for translating age to DQ caterogires
  ageCat <- data.frame("age" = c(18:22, "23_25", 26),
                       "cat" = 1:7)
  
  #Convert age to their corresponding DQ categories
  selfAge <- sapply(age, function(x)
    ifelse(x >= 26, 7, ifelse(x >= 23 & x <= 25, 6,
                              ageCat$cat[match(x, ageCat$age)])))
  
  #Determine whether each potential mate meets the agent's DQ disqualifier
  ageDq <- sapply(selfAge, function(x)
    ifelse(x %in% which(ageDq == 1), 1, 0))
  
  
  
  #Race:
  
  #Determine how many MV points each potential mate should receive based on race/ethnicity
  raceDqMV <- apply(race, 1, function(x)
    ifelse(sum(
      as.numeric(raceDq) * as.numeric(x), na.rm = T
    ) > 0, 0, 2))
  
  
  
  #Religion:
  
  #Determine how many MV points each potential mate should received based on religion
  religionDqMV <- sapply(religion, function(x)
    ifelse(x %in% which(religionDq == 1), 0, 2))
  
  
  #Politics:
  
  #Determine how many MV points each potential mate should received based on politics
  politicsDqMV <- sapply(politics, function(x)
    ifelse(x %in% which(politicsDq == 1), 0, 2))
  
  
  #International status
  intDq <- sapply(int, function(x)
    ifelse((x == 0 & intDQ[1]==1) | 
             (x ==1 & intDQ[2]==1),
           1,0
    )
  )
  
  
  #Add DQs to mv total and compute distance
  mv <- sqrt(mv +
               raceDqMV ^ 2 +
               religionDqMV ^ 2 +
               politicsDqMV ^ 2)
  
  #Compute MV including preferences and disqualifiers
  mv <- (-1 * mv + sqrt(10 ^ 2 * 18)) / sqrt(10 ^ 2 * 18)
  
  #Zero out MV for potential mates who do not meet age or international status DQs
  mv <- mv * ageDq * intDq
  
  return(mv)
  
}


#Improved Sampling#
#A sample function that will return a single scalar if given it
resample <- function(x, ...) {
  
  if (length(x) == 1) {
    x
  } else {
    sample(x, ...)
  }
  
}



mateChoice <- function(data) {
  
  
  #Break data into females and males
  females <- data[data$sex == 0, ]
  males <- data[data$sex == 1, ]
  
  #Determine how many participants we have of each sex
  nFemales<-nrow(females)
  nMales<-nrow(males)
  
  ###MV Calculation###
  
  #Males
  #Calculate the mate value of each female to each male given starting preferences
  maleMvMatrix <- t(apply(males, 1, function(x)
    mvCalc(x[53:67],
           x[27:33],
           x[34:39],
           x[40:50],
           x[20:26],
           x[51:52],
           females[,68:82],
           females[,2],
           females[,10:15],
           females[,17],
           females[,18],
           females[,19])))
  
  
  
  #Females
  #Calculate the mate value of each male to each female given starting preferences
  femaleMvMatrix <- t(apply(females, 1, function(x)
    mvCalc(x[53:67],
           x[27:33],
           x[34:39],
           x[40:50],
           x[20:26],
           x[51:52],
           males[,68:82],
           males[,2],
           males[,10:15],
           males[,17],
           males[,18],
           males[,19])))
  
  
  
  ### Observation Trials ###
  
  #Generate dataframes to store the number of visits
  investMale <- matrix(1, nrow(males), nrow(females))
  investFemale <- matrix(1, nrow(females), nrow(males))
  
  #Generate matrices to track history of reciprocity
  recipHistMale <- matrix(1, nrow(males), nrow(females))
  recipHistFemale <- matrix(1, nrow(females), nrow(males))
  
  #Loop through observation opportunities
  for (o in 1:nobs) {
    mReward <- maleMvMatrix * recipHistMale
    fReward <- femaleMvMatrix * recipHistFemale
    
    #Choose the partner with the highest MV, weighted by reciprocity
    choiceMale <- cbind(1:nrow(males),
                        apply(mReward, 1, function(x)
                          resample(which(x == max(
                            x
                          )), 1)))
    
    choiceFemale <- cbind(1:nrow(females),
                          apply(fReward, 1, function(x)
                            resample(which(x == max(
                              x
                            )), 1)))
    
    #Update observation counts
    investMale[choiceMale] <- investMale[choiceMale] + 1
    investFemale[choiceFemale] <- investFemale[choiceFemale] + 1
    
    #Update reciprocity histories
    recipHistMale <- (t(investFemale) / investMale)
    recipHistFemale <- (t(investMale) / investFemale)
    
  }
  
  
  #Determine which female in which each males has invested most
  #Break ties randomly
  mChoice <- data.frame("male" = 1:nrow(males))
  mChoice$choice <- apply(investMale, 1, function(x)
    resample(which(x == max(x)), 1))
  
  #Determine which male in which each female has invested most
  #Break ties randomly
  fChoice <- data.frame("female" = 1:nrow(females))
  fChoice$choice <- apply(investFemale, 1, function(x)
    resample(which(x == max(x)), 1))
  
  
  #Determine which choices represent a mutual match
  mChoice$match <- (1:nrow(males)) == fChoice$choice[mChoice$choice]
  fChoice$match <- (1:nrow(females)) == mChoice$choice[fChoice$choice]
  
  #Add chosen mate PINs to the male and female dataframes
  males$mPIN <- females$PIN[mChoice$choice]
  females$mPIN <- males$PIN[fChoice$choice]
  
  males$mPIN[mChoice$match == 0] <- NA
  females$mPIN[fChoice$match == 0] <- NA
  
  #Output the data with matches
  return(rbind(females, males))
}

```



```{r analysis}

dataMatched<-mateChoice(data)

dataMatched<-dataMatched[complete.cases(dataMatched$mPIN),]

```



```{r save}

#Timestamp the filename:

path<-"model-outputs/csm-match-human-data-MATCHED-"

format<-".csv"
date<-format(Sys.time(),format="%Y%m%d-%H%M%S")
file<-file.path(paste0(path,date,format))

write.csv(dataMatched,file=file,row.names=F)

```
