---
title: "CSM-Match Scheduling Script"
author: "Dan Conroy-Beam"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r packages}

#Reshape2
#For melting and casting
library(reshape2)
```



```{r parameters}

#Links to the two versions of the Qualtrics survey. One for random matches and the other for model matches
randLink<-"ucsb.qualtrics.com/test?cond=s&PIN="
matchLink<-"ucsb.qualtrics.com/test?cond=r&PIN="

```



## Participant Data

```{r participantLoad}

#Load in the column names
participantHeader<-read.csv("mock-data/scheduling/mock-data/mock-participant-scheduling-data-20230828.csv",nrows=1,header=F)

#Load in the participant data
participant<-read.csv("mock-data/scheduling/mock-data/mock-participant-scheduling-data-20230828.csv",skip=3,header=F)

#Label columns
colnames(participant)<-participantHeader

#Remove unnecessary columns
participant<-participant[,-c(1:17)]

#Create a dummy PIN variable (just for mock data)
participant$PIN<-c(sample(1:50),sample(51:100))

#Load participant data
pData<-read.csv("mock-data/scheduling/mock-data/mock-scheduling-pData-20230828.csv")

#Add in participant sex from pData
participant$sex<-pData$sex[match(pData$PIN,participant$PIN)]

#Add in matched PIN from pData
participant$match<-pData$match[match(pData$PIN,participant$PIN)]

#Add in first name from pData
participant$firstName<-pData$firstName[match(pData$PIN,participant$PIN)]

#Rearrange
participant<-participant[,c(113:116,1:112)]

#Extract all time slots
times<-gsub("_1","",colnames(participant)[seq(5,116,7)])
times<-gsub("avail","",times)

#Relabel timeslot columns more intuitively
colnames(participant)[-(1:4)]<-paste0(c("m","t","w","th","f","s","su"),rep(times,each=7))
```




## Determine Participant Scheduling Blocks

```{r raBlock}

#Melt blocks dataframe
blocks<-melt(participant,id.vars=c("PIN","match","sex","firstName"),
         variable.name="time",
         value.name="avail")

#Re-arrange levels of the time variable
blocks$time<-factor(blocks$time,levels=unique(blocks$time)[sapply(1:7,function(x) seq(x,112,7))])

#Re-arrange dataset
blocks<-blocks[order(blocks$PIN,blocks$time),]

#Set NAs to 0
blocks$avail[is.na(blocks$avail)]<-0

#Create a variable to track blocks of time people are available
#A block is 1 consecutive hour of available time
blocks$block<-0

for(t in 1:nrow(blocks)){
  #Label as a block only if the blocks is available for a full hour
  blocks$block[t]<-ifelse(blocks$avail[t]==1 &
                                 (blocks$avail[t+1]==1 & 
                                    blocks$PIN[t+1] == blocks$PIN[t] &
                           substr(blocks$time[t+1],1,1) == substr(blocks$time[t],1,1)),1,0)
}

#Change any NAs to 0
blocks$block[is.na(blocks$block)]<-0

#Remove any timeslots that are not a block for blocks
blocks<-blocks[blocks$block==1,]

```




## Limit Blocks by Match

Limit to blocks of time when Ps are available with their match and an RA

```{r limitBlocks}

#Create a copy of blocks for matched partners
blocksMatched<-blocks

#Add a vector reflecting co-availability of the mate
blocksMatched$matchAvail<-0

#Loop through blocks
for(i in 1:nrow(blocksMatched)){
  
  #Identify the match's available blocks
  matchBlocks<-blocksMatched[blocksMatched$PIN==blocksMatched$match[i],]
  
  #Determine if the focal block is in the match's blocks
  blocksMatched$matchAvail[i]<-blocksMatched$time[i] %in% matchBlocks$time
  
}

#Limit only to blocks where both participants are available
blocksMatched<-blocksMatched[blocksMatched$matchAvail==1,]

#Label the condition
blocksMatched$condition="match"

```


## Random matches

```{r randomMatches}

#Create a vector of male PINs
malePINs<-unique(blocksMatched$PIN[blocksMatched$sex==1])

#Create a copy of the blocks dataframe for random matches
blocksRand<-blocks

blocksRand$match<-NA

#Loop through female PINs...
for(i in unique(blocksMatched$PIN[blocksMatched$sex==0])){
  
  #Pull out the viable blocks for the focal female
  focalBlocks<-blocks[blocks$PIN==i,]
  
  #Create a variable to track whether she's been matched
  matched<-0
  
  #Create a variable to track the number of random match attempts
  attempts<-0
  
  #If any males are left to pair...
  if (length(malePINs) > 1) {
    
    #As long as she is unmatched...
    while (matched == 0) {
      
      #Increment attempts by 1
      attempts<-attempts+1
      
      #Temporarily pair this female with a random available male who is not her match
      matchTest <- sample(malePINs[malePINs != focalBlocks$match[1]], 1)
      
      #Find the timeslots this mate is available
      matchBlocks <- blocks[blocks$PIN == matchTest, ]
      
      #If the two are jointly available at least once...
      if (sum(sapply(focalBlocks$time, function(x)
        x %in% matchBlocks$time)) > 0) {
        
        #Mark that they have been matched
        matched <- 1
        
        #Remove this male from the possible matches
        malePINs <- malePINs[malePINs != matchTest]
        
        #And add his PIN to the blocks dataframe
        blocksRand$match[blocksRand$PIN == i] <- matchTest
        
        #Otherwisekeep trying
      } else if(attempts>15){
        
        #Quit after 15 failed attempts
        break
        
      }
      
    }
    
  } else {
    
    #If just 1 male is left, pair the female with him
    blocksRand$match[blocksRand$PIN == i] <- malePINs
    
  }
  
}

#Pair males with their new random matches
for(i in 1:nrow(blocksRand)){
  if(blocksRand$sex[i]==1){
    blocksRand$match[i]<-blocksRand$PIN[blocksRand$match==blocksRand$PIN[i]][1]
  }
}

#Remove any participants who failed to match
blocksRand<-blocksRand[complete.cases(blocksRand$match),]


#Add a vector reflecting co-availability of the random mate
blocksRand$matchAvail<-0

#Loop through blocks
for(i in 1:nrow(blocksRand)){
  
  #Identify the random match's blocks for this block
  matchBlocks<-blocksRand[blocksRand$PIN==blocksRand$match[i],]
  
  #Determine if the focal block is in the random match's blocks
  blocksRand$matchAvail[i]<-blocksRand$time[i] %in% matchBlocks$time
  
}

#Limit only to blocks where both participants are available
blocksRand<-blocksRand[blocksRand$matchAvail==1,]

#Label the condition
blocksRand$condition<-"rand"

```



# Final Scheduling  

Compile all schedule information into a final scheduling spreadsheet

```{r scheduling}

#Isolate all female PINs
femalePINs<-unique(participant$PIN[participant$sex==0])

#Limit to females who have a viable matched partner
femalePINs<-femalePINs[femalePINs %in% blocksMatched$PIN]

#And to females who have a viable rnadom partner
femalePINs<-femalePINs[femalePINs %in% blocksRand$PIN]


#Create a blank dataframe for storing final matches
blocksFinal<-rbind(blocksMatched[blocksMatched$PIN %in% femalePINs,],
                   blocksRand[blocksRand$PIN %in% femalePINs,])

#Cast back to wide format
blocksFinalWide<-dcast(blocksFinal,PIN+match+sex+condition~time,
                   value.var="avail")

```



```{r saveData}

#Create a dataframe storing the assigned matches and conditions
matches<-blocksFinalWide[,c(1:2,4)]

#Relabel the PINs
colnames(matches)[1:2]<-c("fPIN","mPIN")



#Create a dataframe for the scheduling spreadsheet
scheduleSheet<-blocksFinalWide

#Relabel the PINs
colnames(scheduleSheet)[1:2]<-c("fPIN","mPIN")

#Add female emails to scheduling sheet
scheduleSheet$fEmail<-pData$email[match(scheduleSheet$fPIN,pData$PIN)]

#Add male emails to scheduling sheet
scheduleSheet$mEmail<-pData$email[match(scheduleSheet$mPIN,pData$PIN)]

#Add female names to scheduling sheet
scheduleSheet$fFirstName<-pData$firstName[match(scheduleSheet$fPIN,pData$PIN)]

#Add female names to scheduling sheet
scheduleSheet$mFirstName<-pData$firstName[match(scheduleSheet$mPIN,pData$PIN)]

#Add female qualtrics link to scheduling sheet
scheduleSheet$fLink<-sapply(1:nrow(scheduleSheet),function(x)
  ifelse(scheduleSheet$condition[x]=="match",paste0(matchLink,scheduleSheet$fPIN[x],"_",scheduleSheet$mPIN[x]),
         paste0(randLink,scheduleSheet$fPIN[x],"_",scheduleSheet$mPIN[x])))

#Add male qualtrics link to scheduling sheet
scheduleSheet$mLink<-sapply(1:nrow(scheduleSheet),function(x)
  ifelse(scheduleSheet$condition[x]=="match",paste0(matchLink,scheduleSheet$mPIN[x],"_",scheduleSheet$fPIN[x]),
         paste0(randLink,scheduleSheet$mPIN[x],"_",scheduleSheet$fPIN[x])))

#Remove the sex and condition columns
scheduleSheet<-scheduleSheet[,-c(3:4)]

#Isolate columns
#Need to do this because the number of available times can vary depending on matches
scheduleSheetContact<-scheduleSheet[,c("fPIN","mPIN","fFirstName","mFirstName","fEmail","mEmail","fLink","mLink")]
scheduleSheetTimes<-scheduleSheet[,!(colnames(scheduleSheet) %in% colnames(scheduleSheetContact))]

#Put back together
scheduleSheet<-cbind(scheduleSheetContact,scheduleSheetTimes)

#Create variables for randomizing order of participants in scheduling sheet
scheduleSheet$rand<-runif(nrow(scheduleSheet),0,1)
scheduleSheet$PINrand<-rep(runif(nrow(scheduleSheet)/2,0,1),each=2)

#Randomly scramble scheduling sheet by PIN and condition to present any possible order effects
scheduleSheet<-scheduleSheet[order(scheduleSheet$PINrand,scheduleSheet$rand),]

#Remove randomizing variables
scheduleSheet<-scheduleSheet[,-tail(1:ncol(scheduleSheet),2)]

#Add in additional scheduling columns
scheduleSheet<-cbind(scheduleSheet,data.frame("contacted"="N",
                                              "contactedBy"="Your Name Here",
                                              "scheduled"="N",
                                              "scheduledBy"="Your Name Here",
                                              "sessionDate"="Session Date Here",
                                              "sessionTime"="Session Time Here",
                                              "sessionRA"="Your Name Here",
                                              "sessionCompleted"="N"))

#Rearrange
scheduleSheet<-scheduleSheet[,c(1:8,115:122,9:114)]

```

