---
title: "CSM Match N Modeling"
author: "Dan Conroy-Beam"
date: "2023-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```






```{r parameters}

#Human Data#
#Load in the human data for parameterizing agents
hdata<-read.csv(file="Human Data/Processed Data/CAREER2P PROCESSED Data 08262020 114326.csv")

hdata<-hdata[,c(1,3:11,199:214,277:292)]

hdata<-hdata[complete.cases(hdata[,c(11:42)]),]



#Population Size#
#The total number of agents to-be generated
popsize<-2000



#Group Size#
#Determines the size of the subgroups agents will be sorted into
groups<-c(100,50,25,20,10,5,4,2)
gsizes<-popsize/groups


#Number of times to repeat pairing loops
loops<-3



#The number of full population matches to compare group matches to
topn<-10



#Create a dataframe to store rematch rates
rematch<-matrix(NA,loops,length(gsizes))
colnames(rematch)<-gsizes

```






```{r functions}
#Agent generation#

agentgenerate<-function(popsize,sex,data){
  
  #Generate agents with trait and preferences by resampling from the human data
  agents<-apply(data[,c(11:42)],2,function(x) sample(x,popsize,replace=T))
  
  agents<-t(apply(agents,2,scale))
  
  #Create a copy of the human dataframe including just the required variables 
  hdata1<-data[,c(11:42)]

  #Calculates the correlation matrix for traits and preferences in the real data
  hdata1cor<-cor(hdata1)
  
  #Computes the Cholesky decomposition of this matrix
  #This will be used to impose a realistic covariance matrix on the simulated data
  hdata1chol<-t(chol(hdata1cor))
  
  #Multiplies the scaled agent data by the Cholesky decomposition, which imposes approximately the correct covariance matrix
  agents<-t(hdata1chol %*% agents)
  
  #Add the mean of each variable to the simulated data to re-center data
  agents<-sapply(1:ncol(agents),function(x) (sd(hdata1[,x])*agents[,x])+mean(hdata1[,x]))
  
  #Truncate rated variables to the true minimum and maximum found in the human data
  agents<-sapply(1:ncol(agents),function(x) ifelse(agents[,x]>max(hdata1[,x]),max(hdata1[,x]),agents[,x]))
  agents<-sapply(1:ncol(agents),function(x) ifelse(agents[,x]<min(hdata1[,x]),min(hdata1[,x]),agents[,x]))
  
  #Names variables appropriately
  colnames(agents)<-colnames(hdata1)
  
  #Set the agent's sex
  sex<-sex
  
  return(as.data.frame(cbind(sex,agents)))
}



#Attraction calculation#
mvcalc<-function(ideal,traits){
  #ideal is ideal preferences
  #traits is actual trait values

  #Calculates the Euclidean distance between the agent's preferences and each mate's traits
  #Transforms this distance such that positive values are more attractive by multiplying by -1 and adding 1 plus the maximum possible Euclidean distance
  mv<-apply(traits,1,function(x) 10*(-1*(dist(rbind(ideal,x)))+sqrt(10^2*16))/sqrt(10^2*16))

  
  return(mv)
  
}



#Improved Sampling#
#A sample function that will return a single scalar if given it
resample <- function(x,...){if(length(x)==1) x else sample(x,...)}

```







```{r model}

#Repeat loops times
for(l in 1:loops){
  
  ###Agent Generation###

  #Generate agents
  males<-agentgenerate(popsize/2,1,hdata[hdata$sex==1,])
  females<-agentgenerate(popsize/2,0,hdata[hdata$sex==0,])
  
  #Give each agent a unique PIN
  males$PIN<-sample(1:nrow(males),nrow(males),replace=F)
  females$PIN<-sample(nrow(males):(nrow(males)+nrow(females)),nrow(females),replace=F)
  
  
    
  #Mate Value Calculation#
  
  #Males
  #Calculate how attracted each male is to each female
  
  maleAttMatrix<-t(apply(males,1,function(q) mvcalc(q[2:17],females[,c(18:33)])))
  
  colnames(maleAttMatrix)<-females$PIN
  rownames(maleAttMatrix)<-males$PIN
  
  #Females
  #Calculate how attracted each female is to each male
  
  femaleAttMatrix<-t(apply(females,1,function(q) mvcalc(q[2:17],males[,c(18:33)])))
  
  colnames(femaleAttMatrix)<-males$PIN
  rownames(femaleAttMatrix)<-females$PIN
  

  
  #Mate Choice#
  
  #Create a dataframe to store the top n matches for each agent
  popMatches<-cbind(females$PIN,matrix(NA,nrow(females),topn))
  
  #Create a copy of the attraction matrices
  maleAttMatrix2<-maleAttMatrix
  femaleAttMatrix2<-femaleAttMatrix
  
  for(t in 1:topn){
      
    #Generate a dataframe for second pairings
    popPairs<-matrix(NA,1,(ncol(males)+ncol(females)))
    
    #Name the pairs dataframe for cbinding
    colnames(popPairs)<-c(colnames(females),colnames(males))
    
    
    #Generate dataframes to store the number of visits
    investMale<-matrix(1,nrow(males),nrow(females))
    investFemale<-matrix(1,nrow(females),nrow(males))
    
    #Generate matrices to track history of reciprocity for RWTS
    recipHistMale<-matrix(1,nrow(males),nrow(females))
    recipHistFemale<-matrix(1,nrow(females),nrow(males))
    
    
    
    #Determine how many observations agents will have to allocate
    nobs<-(popsize/2)*30
    
    #Loop through observation opportunities        
    for(o in 1:nobs){
      
      mReward<-maleAttMatrix2*recipHistMale
      fReward<-femaleAttMatrix2*recipHistFemale
      
      #Choose the partner with the highest MV, weighted by reciprocity
      choiceMale<-cbind(1:nrow(males),
                        apply(mReward,1,function(x)
                              resample(which(x==max(x)),1)))
      
      choiceFemale<-cbind(1:nrow(females),
                          apply(fReward,1,function(x)
                                resample(which(x==max(x)),1)))
      
      #Update observation counts
      investMale[choiceMale]<-investMale[choiceMale]+1
      investFemale[choiceFemale]<-investFemale[choiceFemale]+1
      
      #Update reciprocity histories
      recipHistMale<-(t(investFemale)/investMale)
      recipHistFemale<-(t(investMale)/investFemale)
      
    }
      
    
    #Determine which female each male has chosen
    #Break ties randomly
    mChoice<-data.frame("male"=1:nrow(males))
    mChoice$choice<-apply(investMale,1,function(x)
                          resample(which(x==max(x)),1))
    
    #Determine which male each female has chosen
    #Break ties randomly
    fChoice<-data.frame("female"=1:nrow(females))
    fChoice$choice<-apply(investFemale,1,function(x)
                          resample(which(x==max(x)),1))
    
    #Loop through females' choices
    for(p in 1:nrow(fChoice)){
      
      #Determine the male chosen by the current focal female
      chosenMale<-fChoice$choice[p]
      
      #Determine the female chosen by the focal female's choice
      chosenFemale<-mChoice$choice[chosenMale]
      
      #If the chosen female is the focal female...
      if(chosenFemale==p){
        #Pair the male and female together
        popPairs<-rbind(popPairs,cbind(females[p,],males[chosenMale,]))
      }
      
      #Otherwise do nothing
      
    }
    
    #Remove the row of NAs from the pairs dataframe
    popPairs<-popPairs[-1,]
    
    #Add the current round of pairings into the popMatches matrix
    popMatches[,t+1]<-popPairs[match(popMatches[,1],popPairs[,34]),68]
    
    #Set the mv of the chosen mates to 0
    femaleAttMatrix2[cbind(match(popMatches[,1],row.names(femaleAttMatrix2)),
                          match(popMatches[,t+1],colnames(femaleAttMatrix2))
                          )]<-0
    
    maleAttMatrix2[cbind(match(popMatches[,t+1],row.names(maleAttMatrix2)),
                      match(popMatches[,1],colnames(maleAttMatrix2))
                      )]<-0
    
  }
  
  
  


  #Loop through gsizes
  for(g in gsizes){
    
    #Determine how many groups there will be
    ngroups<-popsize/g
    
    #Assign each male and female to a random population subgroup
    males$group<-sample(rep(1:ngroups,g/2))
    females$group<-sample(rep(1:ngroups,g/2))
    
    
    
    ###Subgroup Mate Choice###
    
    #First generate one dataframe to store initial pairs
    gPairs<-matrix(NA,1,(ncol(males)+ncol(females)))
    
    #Name the pairs dataframe for cbinding
    colnames(gPairs)<-c(colnames(females),colnames(males))
    
    #Loop through groups
    for(r in 1:ngroups){
      
      #Separate out agents in the current group
      malesg<-males[males$group==r,]
      femalesg<-females[females$group==r,]
      
      maleAttMatrixg<-maleAttMatrix[row.names(maleAttMatrix) %in% malesg$PIN,
                                    colnames(maleAttMatrix) %in% femalesg$PIN]
      
      femaleAttMatrixg<-femaleAttMatrix[row.names(femaleAttMatrix) %in% femalesg$PIN,
                                    colnames(femaleAttMatrix) %in% malesg$PIN]
      
      #Mate Choice#
      
      #Generate dataframes to store the number of visits
      investMale<-matrix(1,nrow(malesg),nrow(femalesg))
      investFemale<-matrix(1,nrow(femalesg),nrow(malesg))
      
      #Generate matrices to track history of reciprocity for RWTS
      recipHistMale<-matrix(1,nrow(malesg),nrow(femalesg))
      recipHistFemale<-matrix(1,nrow(femalesg),nrow(malesg))
      
      #Set the number of mate choice observations based on group size
      nobs<-(g/2)*100
      
      #Loop through observation opportunities        
      for(o in 1:nobs){
        
        mReward<-maleAttMatrixg*recipHistMale
        fReward<-femaleAttMatrixg*recipHistFemale
        
        #Choose the partner with the highest MV, weighted by reciprocity
        choiceMale<-cbind(1:nrow(malesg),
                          apply(mReward,1,function(x)
                                resample(which(x==max(x)),1)))
        
        choiceFemale<-cbind(1:nrow(femalesg),
                            apply(fReward,1,function(x)
                                  resample(which(x==max(x)),1)))
        
        #Update observation counts
        investMale[choiceMale]<-investMale[choiceMale]+1
        investFemale[choiceFemale]<-investFemale[choiceFemale]+1
        
        #Update reciprocity histories
        recipHistMale<-(t(investFemale)/investMale)
        recipHistFemale<-(t(investMale)/investFemale)

      }
    
      #A blank dataframe for storing the paired couples
      pairs<-matrix(NA,1,(ncol(malesg)+ncol(femalesg)))
      pairs<-as.data.frame(pairs)
      
      #Name the pairs dataframe for cbinding
      colnames(pairs)<-c(colnames(femalesg),colnames(malesg))
      
      #Determine which female each male has chosen
      #Break ties randomly
      mChoice<-data.frame("male"=1:nrow(malesg))
      mChoice$choice<-apply(investMale,1,function(x)
                            resample(which(x==max(x)),1))
      
      #Determine which male each female has chosen
      #Break ties randomly
      fChoice<-data.frame("female"=1:nrow(femalesg))
      fChoice$choice<-apply(investFemale,1,function(x)
                            resample(which(x==max(x)),1))
      
      #Loop through females' choices
      for(p in 1:nrow(fChoice)){
        
        #Determine the male chosen by the current focal female
        chosenMale<-fChoice$choice[p]
        
        #Determine the female chosen by the focal female's choice
        chosenFemale<-mChoice$choice[chosenMale]
        
        #If the chosen female is the focal female...
        if(chosenFemale==p){
          #Pair the male and female together
          pairs<-rbind(pairs,cbind(femalesg[p,],malesg[chosenMale,]))
        }
        
        #Otherwise do nothing
        
      }
      
      #Remove the row of NAs from the pairs dataframe
      pairs<-pairs[-1,]
      
      gPairs<-rbind(gPairs,pairs)
        
    }
    
    #Remove the first row of the pairs dataframe
    gPairs<-gPairs[-1,]
    
    #Reorder the matches by popMatches
    gMatches<-gPairs[match(popMatches[,1],gPairs[,34]),69]
    
    #Store the proportion of matches that are in the full population top 10
    rematch[l,which(gsizes==g)]<-mean(sapply(1:length(gMatches),function(x)
      gMatches[x] %in% popMatches[x,-1]
      ))
  }

}

```


```{r save}

run<-1:loops

rematch<-cbind(popsize,run,rematch)

write.csv(rematch,"Model Outputs/CSM Match N Modeling Re-Match Results.csv",row.names=F)

```